### ISSUE TITLE
Add a docker-wrapped postgres

### ISSUE THREAD

**Issue by Ebonsignori** [priority-vote/app#4]
I'll help with this one.

In `api` create a `docker-compose.yml` file and add the following 

```yaml
version: "3"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    restart: always
    volumes:
      - "./container_volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
```

Make sure that the each value grabbed via templating, like ${name_here} is added to your `api`'s `.env`, like so

.env
```
# Database Config
DB_HOST=localhost
DB_PORT=5437
DB_NAME=db-core
DB_USER=root
DB_PASSWORD=root
POSTGRES_VERSION=12
``` 

The specific values don't matter (other than DB_HOST and POSTGRES_VERSION) as values like `POSTGRES_DB` `POSTGRES_USER` and `POSTGRES_PASSWORD` are set from the .env file when you run `docker-compose up`. This means a local database is set up with these values, and you grab and use them in your `api` application code to connect to the database
